---
# -- Which phase to run this diagnostic. Valid options: `beforeDependencies`, `afterDependencies`, `beforeSubject`, `afterSubject`, `beforeTest`, `afterTest`, `final`
# @section -- Diagnostics
phases: [final]

# -- Should diagnostics run only on failures or always. Valid options: `onFailure`, `always`.
# @section -- Diagnostics
when: onFailure

# -- Use log line grouping, to improve log readability on [GitHub](https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#grouping-log-lines).
# @section -- Diagnostics
useLogGrouping: true

# -- Commands to run, only `kubectl get`, `kubectl logs`, `helm list`
commands: []