---
name: Test Doc Generator

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
    paths: [tools/doc-generator/**]
  pull_request:
    paths: [tools/doc-generator/**]
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: 'false'

      - name: Run tests
        working-directory: tools/doc-generator
        run: make test
